application: murstsjp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /
  static_files: index.html
  upload: index\.html

- url: /css
  static_dir: static/css
